name: Build

on:
    pull_request:
        paths-ignore:
            - "adr/**"
            - "docs/**"
            - "*.md"
    workflow_dispatch: ~
    schedule:
        - cron: '0 3 * * *'  # Daily at 03:00 UTC
    push:
        branches-ignore:
            - 'dependabot/**'
            - 'upmerge/**'

concurrency:
    group: ci-${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

permissions:
    contents: read
    packages: write

jobs:
    static-checks:
        name: Static checks
        uses: ./.github/workflows/ci_static-checks.yaml
        with:
            type: minimal
    ci:
        name: Tests
        needs: static-checks
        uses: ./.github/workflows/ci.yaml
        with:
            type: minimal
    ci-js:
        name: Javascript Tests
        needs: static-checks
        uses: ./.github/workflows/ci_js.yaml
        with:
            type: minimal

    build-images:
        if: github.event_name != 'pull_request'
        needs:
            - ci
        uses: ./.github/workflows/build_images.yaml
        secrets: inherit

    deploy-stage:
        if: github.event_name != 'pull_request' && github.ref_name == 'develop'
        needs:
            - build-images
        uses: ./.github/workflows/deploy_app.yaml
        with:
            environment_name: stage
            env_file: stage
        secrets: inherit

    deploy-production:
        if: github.event_name != 'pull_request' && github.ref_name == 'main'
        needs:
            - build-images
        uses: ./.github/workflows/deploy_app.yaml
        with:
            environment_name: production
            env_file: prod
        secrets: inherit
